apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - port: 4444
    targetPort: 4444

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: viniciusks13/my_app
        imagePullPolicy: Always
        ports:
        - containerPort: 4444

# comando deletar
# kubectl delete deployment my-app && kubectl delete svc my-app-service