apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - port: 8081
    targetPort: 8081

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: viniciusks13/my_app:test
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

# comando deletar
# kubectl delete rc my-app && kubectl delete svc my-app-service